import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'vehicles',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'vin', type: 'string', isIndexed: true },
        { name: 'chassis_number', type: 'string', isOptional: true },
        { name: 'engine_number', type: 'string', isOptional: true },
        { name: 'make', type: 'string' },
        { name: 'model', type: 'string' },
        { name: 'year', type: 'number' },
        { name: 'vehicle_type', type: 'string' },
        { name: 'current_odometer', type: 'number' },
        { name: 'unit', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'assigned_route', type: 'string', isOptional: true },
        { name: 'depot_location', type: 'string', isOptional: true },
        { name: 'synced', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'work_orders',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'work_order_number', type: 'string', isIndexed: true },
        { name: 'vehicle_id', type: 'string', isIndexed: true },
        { name: 'description', type: 'string' },
        { name: 'priority', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'requested_by', type: 'string' },
        { name: 'assigned_to', type: 'string', isOptional: true },
        { name: 'started_at', type: 'number', isOptional: true },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'total_labor_hours', type: 'number', isOptional: true },
        { name: 'total_cost', type: 'number', isOptional: true },
        { name: 'synced', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'inspections',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'vehicle_id', type: 'string', isIndexed: true },
        { name: 'inspector_id', type: 'string' },
        { name: 'checklist_id', type: 'string' },
        { name: 'inspection_date', type: 'number', isIndexed: true },
        { name: 'odometer_reading', type: 'number' },
        { name: 'overall_status', type: 'string' },
        { name: 'checklist_results', type: 'string' }, // JSON string
        { name: 'defects_reported', type: 'number' },
        { name: 'synced', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'alerts',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'vehicle_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'component_id', type: 'string', isOptional: true },
        { name: 'alert_type', type: 'string', isIndexed: true },
        { name: 'severity', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'synced', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'components',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'vehicle_id', type: 'string', isIndexed: true },
        { name: 'component_type', type: 'string', isIndexed: true },
        { name: 'component_subtype', type: 'string', isOptional: true },
        { name: 'brand', type: 'string', isOptional: true },
        { name: 'model', type: 'string', isOptional: true },
        { name: 'installation_date', type: 'number' },
        { name: 'installation_odometer', type: 'number' },
        { name: 'expected_life_days', type: 'number', isOptional: true },
        { name: 'expected_life_km', type: 'number', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'synced', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'inspection_checklists',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'vehicle_type', type: 'string', isIndexed: true },
        { name: 'checklist_items', type: 'string' }, // JSON string
        { name: 'synced', type: 'boolean', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
